### ISSUE TITLE
"Operation is not supported on this platform." When trying to create cache in .NET MAUI in Mac Catalyst 

### ISSUE THREAD

**Issue by igalfsg** [AzureAD/microsoft-authentication-extensions-for-dotnet#170]
I am trying to port my console app to a .NET MAUI app, and when trying to create the cache in .NET MAUI I get the exception "Operation is not supported on this platform." here is the stack trace:
```
   at Microsoft.Identity.Client.Extensions.Msal.Storage.Create(StorageCreationProperties creationProperties, TraceSource logger)
   at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper..ctor(StorageCreationProperties storageCreationProperties, TraceSource logger, HashSet`1 knownAccountIds, FileSystemWatcher cacheWatcher)
   at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper.CreateAsync(StorageCreationProperties storageCreationProperties, TraceSource logger)
```
This is the code that tries to create the cache:
```
storageProperties = new StorageCreationPropertiesBuilder(AuthCacheConfig.CacheFileName, filePath)
                .WithLinuxKeyring(
                    AuthCacheConfig.LinuxKeyRingSchema,
                    AuthCacheConfig.LinuxKeyRingCollection,
                    AuthCacheConfig.LinuxKeyRingLabel,
                    AuthCacheConfig.LinuxKeyRingAttr1,
                    AuthCacheConfig.LinuxKeyRingAttr2)
                .WithMacKeyChain(
                    AuthCacheConfig.KeyChainServiceName,
                    AuthCacheConfig.KeyChainAccountName)
                .Build();
var cacheHelper = await MsalCacheHelper.CreateAsync(storageProperties).ConfigureAwait(false);
```
dotnet version:6.0.200

**Comment by bgavrilMS** [comment]
Closing as known issue, please track https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3127 for details.
