### ISSUE TITLE
MsalCacheHelper.UserRootDirectory returns empty string when run in Azure function environment

### ISSUE THREAD

**Issue by thealanagrace** [AzureAD/microsoft-authentication-extensions-for-dotnet#202]
When running the following code in an azure function environment:

```
var storageProperties = new StorageCreationPropertiesBuilder(_cacheFileName, MsalCacheHelper.UserRootDirectory).Build();
MsalCacheHelper cache = await MsalCacheHelper.CreateAsync(storageProperties).ConfigureAwait(false);
```

I hit the following exception:

```
Exception: System.ArgumentException: Path cannot be the empty string or all whitespace. (Parameter 'path')
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.Identity.Client.Extensions.Msal.CrossPlatLock..ctor(String lockfilePath, Int32 lockFileRetryDelay, Int32 lockFileRetryCount)
   at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper.CreateCrossPlatLock(StorageCreationProperties storageCreationProperties)
   at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper.CreateAsync(StorageCreationProperties storageCreationProperties, TraceSource logger)
```

While this code had run fine locally, we hit exceptions 100% of the time after deploying this code to our azure function. After some investigations, we realized that `MsalCacheHelper.UserRootDirectory` returns an empty string when in an azure function environment. 

The [MsalCacheHelper.UserRootDirectory](https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/blob/main/src/Microsoft.Identity.Client.Extensions.Msal/MsalCacheHelper.cs) code mentions that this value "Gets the user's root directory across platforms." It would be great if the azure function platform was included here!

**Comment by bgavrilMS** [comment]
Good point, this helper was only ever tested on Windows, Mac and Linux. 

We'd appreciate a contribution to get this to work on Azure Functions, I'm not even sure if "root dir" concept exists in this case.
