### ISSUE TITLE
Extension should not crash on Linux if LibSecret 1.so.0 is not present

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-extensions-for-dotnet#56]
1. Use a machine where LibSecret is not present, e.g. Ubuntu 16.04 Azure version
2. Bind the cache, for example run the ManualTestApp

Actual: 

An exception of type 'System.DllNotFoundException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Unable to load shared library 'libsecret-1.so.0' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibsecret-1.so.0: cannot open shared object file: No such file or directory'
   at Microsoft.Identity.Client.Extensions.Msal.Libsecret.secret_schema_new(String name, Int32 flags, String attribute1, Int32 attribute1Type, String attribute2, Int32 attribute2Type, IntPtr end)
   at Microsoft.Identity.Client.Extensions.Msal.CacheAccessorLinux.GetLibsecretSchema() in /home/bogdan/microsoft-authentication-extensions-for-dotnet/src/Microsoft.Identity.Client.Extensions.Msal/Os/Linux/CacheAccessorLinux.cs:line 148
   at Microsoft.Identity.Client.Extensions.Msal.CacheAccessorLinux.Clear() in /home/bogdan/microsoft-authentication-extensions-for-dotnet/src/Microsoft.Identity.Client.Extensions.Msal/Os/Linux/CacheAccessorLinux.cs:line 31
   at Microsoft.Identity.Client.Extensions.Msal.MsalCacheStorage.ReadData() in /home/bogdan/microsoft-authentication-extensions-for-dotnet/src/Microsoft.Identity.Client.Extensions.Msal/MsalCacheStorage.cs:line 140
   at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper.RegisterCache(ITokenCache tokenCache) in /home/bogdan/microsoft-authentication-extensions-for-dotnet/src/Microsoft.Identity.Client.Extensions.Msal/MsalCacheHelper.cs:line 242
   at ManualTestApp.Program.<CreatePublicClientAndBindCacheAsync>d__4.MoveNext() in /home/bogdan/microsoft-authentication-extensions-for-dotnet/tests/ManualTestApp/Program.cs:line 223

**Comment by yasinlachiny** [comment]
I have the same issue
